# permissions for end users to edit gitrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: git-repo-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitrepository-editor-role
rules:
- apiGroups:
  - vcs.github
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vcs.github
  resources:
  - gitrepositories/status
  verbs:
  - get
